"""Refresh browser cache fingerprints after publishing viewer data.

Run directly after changing an individual docs/data file:
    python3 scripts/update_data_versions.py

The full data builder calls this automatically after its successful final step.
Use --check to verify the manifest without changing any files.
"""
import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_NAMES = (
    "borders", "cities", "land", "polities", "polity_index", "population", "years",
)


def manifest_text(root=ROOT):
    """Hash all seven required files before producing any output."""
    versions = {}
    for name in DATA_NAMES:
        digest = hashlib.sha256()
        with (Path(root) / "docs" / "data" / (name + ".json")).open("rb") as source:
            for chunk in iter(lambda: source.read(1024 * 1024), b""):
                digest.update(chunk)
        versions[name] = digest.hexdigest()[:16]
    return (
        "// Content fingerprints: generated by scripts/update_data_versions.py.\n"
        "export const DATA_VERSIONS = Object.freeze("
        + json.dumps(versions, indent=2)
        + ");\n"
    )


def update_data_versions(root=ROOT, check=False):
    """Write a deterministic manifest, or return whether it is current in check mode."""
    text = manifest_text(root)
    destination = Path(root) / "docs" / "js" / "data-version.js"
    current = destination.read_text(encoding="utf-8") if destination.exists() else None
    if check:
        return current == text
    if current != text:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")
    print("data cache: fingerprints current for 7 published files")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when cache fingerprints need regeneration")
    arguments = parser.parse_args()
    if not update_data_versions(check=arguments.check):
        parser.exit(1, "Data fingerprints are out of date. Run python3 scripts/update_data_versions.py\n")
